name: CI  # Workflow name as it appears in GitHub Actions UI

on:  # Trigger conditions for the workflow
  push:
    branches:  # Trigger only when pushing to the 'main' branch
      - "main"
    paths:  # Only run if files in these paths are changed
      - "chatbot/**"
      - "tests/**"
      - ".github/workflows/**"
  pull_request:  # Trigger on PR events (open, sync, etc.)
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "chatbot/**"
      - "tests/**"
      - ".github/workflows/**"

jobs:
  test:  # Job name is 'test'
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    timeout-minutes: 20  # Stop the job if it exceeds 20 minutes

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Checkout the repository code
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Use PR head branch
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Python
        uses: actions/setup-python@v5  # Setup Python runtime
        with:
          python-version: '3.10.6'  # Use Python 3.10.6

      - name: Get poetry version
        id: poetry-version
        run: echo "poetry-version=$(cat version/poetry)" >> "$GITHUB_OUTPUT"
        # Reads the poetry version from version/poetry file and exposes it to later steps

      - name: Install poetry
        uses: snok/install-poetry@v1  # Install Poetry via reusable action
        with:
          version: ${{ steps.poetry-version.outputs.poetry-version }}
          virtualenvs-in-project: true  # Store .venv in project root (not global)

      - name: Get llama-cpp version
        id: llama-cpp-version
        run: echo "llama-cpp-version=$(cat version/llama_cpp)" >> "$GITHUB_OUTPUT"
        # Reads llama-cpp-python version and stores it as an output variable

      - name: Setup environment
        # Ensure lockfile is up to date, install all deps (no local build)
        # Activate virtualenv and install llama-cpp manually
        run: |
          poetry lock --check  
          poetry install --no-root --no-ansi   
          . .venv/bin/activate && pip3 install llama-cpp-python==${{ steps.llama-cpp-version.outputs.llama-cpp-version }}
          

      - name: Run tests
        # Run all tests with detailed logging and slowest 5 durations
        run: |
          poetry run python -m pytest --durations=5 --log-cli-level=DEBUG --capture=tee-sys -v
          

